name: 'vcpkg'
description: ''
author: ''

runs:
  using: "composite"
  steps:
    - name: Clone vcpkg repository
      run: git clone https://github.com/microsoft/vcpkg
      shell: bash

    - name: Bootstrap vcpkg
      run: |
        if [[ ${{ runner.os }} == 'Windows' ]]; then
          vcpkg/bootstrap-vcpkg.bat
        elif [[ ${{ runner.os }} == 'Linux' || ${{ runner.os }} == 'macOS' ]]; then
          vcpkg/bootstrap-vcpkg.sh
        fi
      shell: bash

    - name: Set VCPKG_ROOT environment variable
      run: |
        if [[ ${{ runner.os }} == 'Linux' || ${{ runner.os }} == 'macOS' ]]; then
          echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
        fi
      shell: bash
      
    - name: Set CMAKE_TOOLCHAIN_FILE environment variable
      run: |
        if [[ ${{ runner.os }} == 'Linux' || ${{ runner.os }} == 'macOS' ]]; then
          echo "CMAKE_TOOLCHAIN_FILE=$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Set VCPKG_ROOT environment variable on windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        if [[ ${{ runner.os }} == 'Windows' ]]; then
          echo echo VCPKG_ROOT=%cd%\vcpkg >> $GITHUB_ENV
        fi
      
    - name: Set CMAKE_TOOLCHAIN_FILE environment variable on windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        echo CMAKE_TOOLCHAIN_FILE=%cd%\vcpkg\scripts\buildsystems\vcpkg.cmake >> $GITHUB_ENV

      

    - name: Print VCPKG_ROOT
      run: |
        echo VCPKG_ROOT is $VCPKG_ROOT
      shell: bash
