name: 'vcpkg'
description: ''
author: ''

runs:
  using: "composite"
  steps:
    - name: Clone vcpkg repository
      run: git clone https://github.com/microsoft/vcpkg
      shell: bash

    - name: Bootstrap vcpkg
      run: |
        if [[ ${{ runner.os }} == 'Windows' ]]; then
          vcpkg/bootstrap-vcpkg.bat
        elif [[ ${{ runner.os }} == 'Linux' || ${{ runner.os }} == 'macOS' ]]; then
          vcpkg/bootstrap-vcpkg.sh
        fi
      shell: bash

    - name: Set VCPKG_ROOT environment variable
      run: echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
      shell: bash

    - name: Print VCPKG_ROOT
      run: echo VCPKG_ROOT is $(pwd)/vcpkg
      shell: bash
